### ISSUE TITLE
Support DataLoader pattern

### ISSUE THREAD

**Issue by ianhoffman** [mwildehahn/hack-graphql#100]
We should support (and encourage) use of the DataLoader pattern to make querying efficient. We'll want to support this on a framework level because so that it integrates with the type-system. In short, I think we'll want something like this:

* Add a new abstract type, `GraphQL\Types\Promise` (or a better name) which expects as its Hack type a `Promise` parameterized by a Hack object.
* Fields annotated with `GraphQL\Field` should be allowed to return a `Promise<HackType>`. A `Promise<HackType>` can be obtained by, for example, calling `DataLoader::load($id)`.
* The `GraphQL\Types\Promise` class's `resolveAsync` invokes the resolver, returning the (unresolved) promise.

We can then do the following:
1. Resolve the request. We'll have a dict containing some number of un-resolved promises.
1. Batch load all pending data.
1. Walk the dict and resolve each promise. (We can avoid walking the entire dict each time.)
1. Repeat 1-3 until there are no more promises to resolve.

We'll need to make this approach work with introspection, too.

**Comment by mwildehahn** [comment]
I don't know that this needs to be a part of this framework. I think we can implement something like the `DataLoader` pattern by leveraging async/await.

I looked into this once before and forgot some of the details, but I think we can do something like this:

```
$result = await DataLoader::getId(1)
```

Where the data loader can call:

```
		await Asio\later();
```

to allow other IDs to be collected before executing.

**Comment by ianhoffman** [comment]
Oh interesting. That makes my work on #101 moot — I had thought we'd need to support something like this ourselves.

If `Asio\later` will work, that'd be great.

**Comment by ianhoffman** [comment]
It would be good to understand exactly when `Asio\later()` kicks in. It's not like we're telling Hack to wake up the coroutine when a certain event occurs, so how does the event loop know when to resume these calls?

**Comment by mwildehahn** [comment]
Found more docs on `Asio\later`: https://docs.hhvm.com/hack/asynchronous-operations/examples#batching

**Comment by mwildehahn** [comment]
Although, this just shows an example, doesn't explain how it works

**Comment by ianhoffman** [comment]
Seems like Jan had a good answer on Slack:

> I don't understand all the technical details, but my rough understanding is that this will put the current Awaitable at the end of the queue, so it will resume after every other pending Awaitable has had a chance to run (e.g. every other Awaitable has added some IDs to fetch to the current batch and called Asio\later).

Sounds like it's exactly what we want.
