### ISSUE TITLE
Support InterfaceType

### ISSUE THREAD

**Issue by jlw5** [mwildehahn/hack-graphql#20]
This will be useful when returning a list of objects, where the objects have some fields in common but are not all of the same type. 

Example: returning a list of ProfileField, where a ProfileField might be a LinkDataField or a DateDataField or a LocationDataField. All ProfileFields will have the same metadata (label, hint, is_protected, etc), but different types of values.

**Comment by ianhoffman** [comment]
Took a first stab at this https://github.com/mwildehahn/hack-graphql/pull/23

**Comment by ianhoffman** [comment]
Closing this out — our implementation can improve, but I think we have v1 support implemented!
