### ISSUE TITLE
Support introspection

### ISSUE THREAD

**Issue by mwildehahn** [mwildehahn/hack-graphql#36]
https://spec.graphql.org/June2018/#sec-Introspection

**Comment by mwildehahn** [comment]
For reference, this is the schema of the GraphQL schema introspection system:
```
type __Schema {
  types: [__Type!]!
  queryType: __Type!
  mutationType: __Type
  subscriptionType: __Type
  directives: [__Directive!]!
}

type __Type {
  kind: __TypeKind!
  name: String
  description: String

  # OBJECT and INTERFACE only
  fields(includeDeprecated: Boolean = false): [__Field!]

  # OBJECT only
  interfaces: [__Type!]

  # INTERFACE and UNION only
  possibleTypes: [__Type!]

  # ENUM only
  enumValues(includeDeprecated: Boolean = false): [__EnumValue!]

  # INPUT_OBJECT only
  inputFields: [__InputValue!]

  # NON_NULL and LIST only
  ofType: __Type
}

type __Field {
  name: String!
  description: String
  args: [__InputValue!]!
  type: __Type!
  isDeprecated: Boolean!
  deprecationReason: String
}

type __InputValue {
  name: String!
  description: String
  type: __Type!
  defaultValue: String
}

type __EnumValue {
  name: String!
  description: String
  isDeprecated: Boolean!
  deprecationReason: String
}

enum __TypeKind {
  SCALAR
  OBJECT
  INTERFACE
  UNION
  ENUM
  INPUT_OBJECT
  LIST
  NON_NULL
}

type __Directive {
  name: String!
  description: String
  locations: [__DirectiveLocation!]!
  args: [__InputValue!]!
}

enum __DirectiveLocation {
  QUERY
  MUTATION
  SUBSCRIPTION
  FIELD
  FRAGMENT_DEFINITION
  FRAGMENT_SPREAD
  INLINE_FRAGMENT
  SCHEMA
  SCALAR
  OBJECT
  FIELD_DEFINITION
  ARGUMENT_DEFINITION
  INTERFACE
  UNION
  ENUM
  ENUM_VALUE
  INPUT_OBJECT
  INPUT_FIELD_DEFINITION
}
```

**Comment by mwildehahn** [comment]
My initial thought for supporting this is defining something like the following set of interfaces:

```

interface IntrospectableSchema {
    public function getTypes(): vec<IntrospectableType>;
    public function getQueryType(): IntrospectableType;
    public function getMutationType(): ?IntrospectableType;
    public function getSubscriptionType(): ?IntrospectableType;
    public function getDirectives(): vec<IntrospectableDirective>
}

interface IntrospectableType {
   public function getTypeKind(): TypeKind;
   public function getName(): ?string;
   public function getDescription(): ?string;
}

interface IntrospectableObject extends IntrospectableType {
    public function getFields(bool $includeDeprecated = false): ?vec<IntrospectableField>;
    public function getInterfaces(): vec<IntrospectableInterface>;
}

interface IntrospectableInterface extends IntrospectableType {
    public function getFields(bool $includeDeprecated = false): IntrospectableField;
    public function getPossibleTypes(): vec<IntrospectableType>;
}

interface IntrospectableEnum extends IntrospectableType {
    public function getEnumValues(bool $includeDeprecated = false): vec<IntrospectableEnumValue>;
}

interface IntrospectableInput extends IntrospectableType {
    public function getInputFields(): vec<IntrospectableInputValue>;
}

// TODO: how to handle ofType? for NON_NULL and LIST?

interface IntrospectableNamedType {
    public function getName(): string;
    public function getDescription(): ?string;
}

interface IntrospectableField extends IntrospectableNamedType {
    public function getArgs(): vec<IntrospectableInputValue>;
    public function getType(): IntrospectableType;
    public function isDeprecated(): bool;
    public function getDeprecationReason: ?string;
}

interface IntrospectableInputValue extends IntrospectableNamedType {
    public function getType(): IntrospectableType;
    public function defaultValue(): ?string;
}

interface IntrospectableEnumValue extends IntrospectableNamedType {
    public function isDeprecated(): bool;
    public function getDeprecationReason: ?string;
}
```

Each object type we generate would implement the relevant interface. I think with that we could hand write a resolver to resolve these two queries:

```
__schema: __Schema!
__type(name: String!): __Type
```

Thoughts?

**Comment by jjergus** [comment]
Would we put `<<GraphQL\Object>>` and `<<GraphQL\Field>>` on these interfaces and their methods and have the existing codegen handle it, or did you plan some other way to expose them?

**Comment by mwildehahn** [comment]
Something like this feels like it is going in the right direction: https://github.com/mwildehahn/hack-graphql/compare/introspection?expand=1.

Maybe we add some special handling for `__Schema` so we can init the correct parent to the generated `Schema` that will implement `IntrospectableSchema`?

**Comment by mwildehahn** [comment]
An adjustment to that would be to not try and resolve `__schema` and `__type` within the `Query` class and have separate handling for that so we don't have to fudge the parent class 🤔

**Comment by jjergus** [comment]
I think it's fine (probably inevitable) that the introspection fields (`__schema` and `__type` on the query root type; `__typename` on every object type) are hardcoded *somewhere*.

Either in the codegen (it'd output some extra fields that were not `<<GraphQL\Field>>` methods on the backing class -- then the runtime wouldn't need to know anything special about these fields); or in runtime code (e.g. the codegen wouldn't output anything special; but the object type/root type base class would run some custom logic if the field name is one of those).

I don't think either option is clearly better, probably just try it and see if the code looks sufficiently simple/clean/typesafe then maybe change it if it ends up being too ugly...

**Comment by jjergus** [comment]
Note that per the GraphQL spec, the introspection types must *not* show up in introspection themselves -- so this is another thing that may need a special case somewhere.

**Comment by jjergus** [comment]
My original idea was to put `<<GraphQL\Object>>` and `<<GraphQL\Field>>` directly on the existing types (e.g. BaseType), but I like your interfaces a lot better. They should give us a really nice way to handle the cases where our existing types don't exactly match what the GraphQL introspection output should be, such as:

- we have 2 classes per scalar/enum (input vs output type) but they are the same introspection type -- we can choose one of them to implement the interface and the other won't
- we have a Nullable wrapper around non-nullable types, but introspection requires a NonNullable wrapper around nullable types -- so we can have our Nullable wrapper class **not** implement this interface and instead create a NonNullable wrapper class that implements the interface, but is not a subclass of BaseType

**Comment by ianhoffman** [comment]
Think we can close this out.
