### ISSUE TITLE
Decide on best practices wrt non-nullable fields

### ISSUE THREAD

**Issue by jjergus** [mwildehahn/hack-graphql#42]
See #39

Currently, fields are nullable by default and people have to use an attribute with an intentionally scary name (`<<KillsParentOnException>>`) to override that. This is the most conservative option but not necessarily the best.

Some possible options:

- current version (discourage non-nullable fields heavily): safe but client developers may not like it because it requires a null check on every field
- change attribute name to less scary (i.e. still discourage non-nullable fields but less heavily)
- get rid of the attribute completely, respect Hack return type nullability (nullable Hack type <-> nullable GraphQL type, like for input types)
  - this *seems* like an obviously correct solution but I wouldn't recommend it -- I think it makes a lot of sense for non-nullable Hack methods to be surfaced as nullable GraphQL fields: the GraphQL field value will be `null` if the Hack method throws an exception
- respect Hack return type nullability for **leaf types** (scalars, enums) but default to nullable for object types (with some way to override both)
  - possibly the best option but could be confusing/non-intuitive
  - advantages:
    - much fewer null checks for client developers
    - the "damage" is limited: a non-nullable field throwing an exception can kill at most 1 parent (unless the developer intentionally overrides the default)
    - scalar/enum-typed fields are often simple getters which never throw anyway
  - disadvantages:
    - confusing/non-intuitive: developers may not understand which of their fields end up being nullable and why (but do they care? do developers expect to understand every nuance of a framework they're using?)

**Comment by ianhoffman** [comment]
Think we can close this out.
