### ISSUE TITLE
decide how to handle hidden exceptions

### ISSUE THREAD

**Issue by jjergus** [mwildehahn/hack-graphql#47]
Currently, any exceptions that are not specifically marked as user-facing (by extending the [`UserFacingError`](https://github.com/mwildehahn/hack-graphql/blob/main/src/UserFacingError.hack#L18) class) are intentionally hidden from GraphQL clients. The assumption is that they might contain sensitive data (like IP addresses) and that GraphQL clients are not guaranteed to be trustworthy (e.g. any public user with a mobile app).

This is, of course, very bad for debugging -- e.g. it is impossible to know why exactly this field failed to resolve: https://github.com/mwildehahn/hack-graphql/blob/main/tests/ErrorTest.hack#L24

This should probably be addressed before people start using the framework, since having non-debuggable errors could be a terrible experience for client developers.

Possible options:

- if the initial prototype is only meant to be used by trusted clients, we could simply stop hiding any exceptions for now
- if we indeed require exceptions to be hidden, there should be *some* way for trusted client developers to see them
  - exceptions can be logged somewhere; when a client developer sees an error they look at recent logs
  - as an optional extra feature, the returned error in the GraphQL response should contain some identifier that the client developer can use to look up the exact error in the logs (in case there are multiple)

**Comment by ianhoffman** [comment]
> if the initial prototype is only meant to be used by trusted clients, we could simply stop hiding any exceptions for now

I think that's the initial intent. Might make sense to just bubble everything up for now, since it'd aid debugging? I think it'd be as simple as passing a `UserFacingError` instead of `FieldResolverError` here: https://github.com/mwildehahn/hack-graphql/blob/main/src/FieldDefinition.hack#L32

**Comment by ianhoffman** [comment]
WDYT @mwildehahn ?

**Comment by mwildehahn** [comment]
I think it's ok to stop hiding exceptions while we have this in a "pre-release". We generally try to be as conservative as possible with errors to avoid leaking data but agree we should optimize for debugging in this case

**Comment by mwildehahn** [comment]
I was working on implementing something on top of this framework yesterday and the hardest bit was getting vague errors about what was going wrong which was usually me just miss typing a field name or not unpacking a value correctly.

I think until we get better request validation it will be useful just to bubble as much detail up.

Maybe we can provide an option to the resolver to not mask errors so we don't take a step back? I could see that being useful in the future.

**Comment by jjergus** [comment]
The hidden errors are stored in the exception instance: https://github.com/mwildehahn/hack-graphql/blob/main/src/UserFacingError.hack#L47

So they are not lost until the very last moment in Resolver before we convert all exceptions to the format required by the GraphQL response. So that might be a good place to put some custom hook that could specify what to do with them (log them, add them to the response, throw them away like we do now...)

**Comment by ianhoffman** [comment]
Decided to go with the custom hook approach (well, an option passed to the resolver, but similar idea).

Closing this out.
