### ISSUE TITLE
Support annotating shapes with GraphQL\ObjectType

### ISSUE THREAD

**Issue by mwildehahn** [mwildehahn/hack-graphql#53]

**Comment by ianhoffman** [comment]
Just a question here - how do you imagine fields working? Is each member of the shape a field (I assume the answer is yes). And then do these fields have no descriptions?

**Comment by jjergus** [comment]
Yeah each shape field would be a GraphQL field. This will add the restriction that each shape field must be of a type that can be translated to a valid GraphQL input **and** output type (scalars, enums, other shapes that are also annotated with both ObjectType and InputObjectType; but no input objects, or object/interface output types) but that should be fine.

> And then do these fields have no descriptions?

For things that can't have attributes (shape fields, but also e.g. method arguments) a decent option is to use docblocks/comments for descriptions (parsed via HHAST probably).

**Comment by jjergus** [comment]
Alternatively something like

```Hack
<<
  GraphQL\Object('User'),
  GraphQL\InputObject<'UserInput'>,
  GraphQL\Descriptions(dict[
    'name' => 'Full name of the user',
    // ...
  ])
>>
newtype User = shape(
  'name' => string,
  // ...
);

**Comment by ianhoffman** [comment]
Closing this and moving the descriptions stuff to #64 .
